spring:
  application:
    name: java-api


  # 1. 配置数据库连接 (固定 URL，方便登录)
  datasource:
    url: jdbc:h2:mem:talk2data       # <--- 记住这个名字，一会儿登录要用
    driver-class-name: org.h2.Driver
    username: sa
    password:                        # 默认为空，不填

  # 2. 开启 H2 Console
  h2:
    console:
      enabled: true                  # <--- 关键！开启控制台
      path: /h2-console              # 访问路径
      settings:
        web-allow-others: true       # 允许远程访问 (可选，本地开发建议开启)


langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com  # 如果用DeepSeek，这里必填
      api-key: sk-7ec0e853c63241d29ac4b374afacf6b8          # 填入你的 Key
      model-name: deepseek-chat         # 或者是 deepseek-chat
      temperature: 0.0                    # SQL生成需要严谨，温度设为0
      log-requests: true                  # 开发时开启日志，方便调试
      log-responses: true